name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -e .
          pip install pytest
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -e .
          pip install pytest
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        shell: bash
        run: |
          python -m venv venv
          source venv/Scripts/activate
          pip install -e .
          pip install pytest
      - name: Run tests
        shell: bash
        run: |
          source venv/Scripts/activate
          pytest

