name: Windows

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        shell: bash
        run: |
          python -m venv venv
          source venv/Scripts/activate
          pip install -e .
          pip install pytest
          pip install pandas
          pip install scipy
      - name: Run tests
        shell: bash
        env:
            PYTHONPATH: ${{ github.workspace }}
        run: |
          source venv/Scripts/activate
          pytest
