name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m venv venv
        if [ "$RUNNER_OS" == "Windows" ]; then
          .\venv\Scripts\activate
        else
          source venv/bin/activate
        fi
        pip install -e .
        pip install pytest
    - name: Run tests
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          .\venv\Scripts\activate
        else
          source venv/bin/activate
        fi
        pytest
